/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    topics: Topic;
    'case-studies': CaseStudy;
    services: Service;
    faqs: Faq;
    media: Media;
    'quote-requests': QuoteRequest;
    'rate-limit-hits': RateLimitHit;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'quote-requests': QuoteRequestsSelect<false> | QuoteRequestsSelect<true>;
    'rate-limit-hits': RateLimitHitsSelect<false> | RateLimitHitsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      purgeLostLeads: TaskPurgeLostLeads;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown on the blog index and in search results. 25 words max.
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  /**
   * Add a "Quote CTA" block around 60% of the way through. If you don’t, one is inserted automatically.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Used in the URL. Generated from the title if left empty.
   */
  slug: string;
  /**
   * Set automatically when first published.
   */
  publishedAt?: string | null;
  topics: (number | Topic)[];
  /**
   * The newest featured post is shown large at the top of /blog.
   */
  featured?: boolean | null;
  series?: string | null;
  author: string;
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  readingTime?: number | null;
  /**
   * Optional. Falls back to the title and summary when empty.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Full URL. Only set when this content lives elsewhere first.
     */
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what the image shows for someone who can’t see it. For purely decorative video loops, describe what happens on screen.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  title: string;
  /**
   * Used in the URL. Generated from the title if left empty.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * One line under the title.
   */
  summary: string;
  /**
   * The problem in 12 words or fewer. Used on cards.
   */
  problemLine: string;
  /**
   * One concrete, verifiable result. Leave empty rather than estimate — cards hide it.
   */
  outcomeLine?: string | null;
  demoUrl?: string | null;
  repoUrl?: string | null;
  /**
   * Screenshot, or a muted video loop (≤ 8s, ≤ 1.5 MB, WebM or MP4).
   */
  coverMedia?: (number | null) | Media;
  /**
   * Poster frame for a video cover (≤ 60 KB).
   */
  coverPoster?: (number | null) | Media;
  /**
   * Shown when there is no cover media.
   */
  coverVisual?:
    | (
        | 'email-row'
        | 'ledger'
        | 'workflow-node'
        | 'kpi-tiles'
        | 'filter-panel'
        | 'slack-message'
        | 'table'
        | 'chart'
        | 'agent-trace'
      )
    | null;
  atAGlance: {
    problem: string;
    solution: string;
    result: string;
  };
  /**
   * 120 words max.
   */
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Top-to-bottom tiers. Every node in a tier connects to the tier below.
   */
  problemDiagram?:
    | {
        nodes?:
          | {
              label: string;
              detail?: string | null;
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  featureShots?:
    | {
        title: string;
        caption: string;
        media?: (number | null) | Media;
        /**
         * Used when there is no screenshot.
         */
        visual?:
          | (
              | 'email-row'
              | 'ledger'
              | 'workflow-node'
              | 'kpi-tiles'
              | 'filter-panel'
              | 'slack-message'
              | 'table'
              | 'chart'
              | 'agent-trace'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Top-to-bottom tiers. Every node in a tier connects to the tier below.
   */
  architecture?:
    | {
        nodes?:
          | {
              label: string;
              detail?: string | null;
              highlight?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Replaces the tiered diagram when set.
   */
  architectureSvg?: (number | null) | Media;
  architectureNotes?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Only real, measured results. The section is hidden when empty — never estimate.
   */
  results?:
    | {
        value: string;
        label: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  stack?:
    | {
        name: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Used in the URL. Generated from the title if left empty.
   */
  slug: string;
  industry: 'retail-distribution' | 'healthcare' | 'marketplaces' | 'professional-services' | 'saas' | 'cross-industry';
  services?: (number | Service)[] | null;
  /**
   * e.g. "6 weeks". Leave empty if unknown.
   */
  timeline?: string | null;
  order?: number | null;
  /**
   * Optional. Falls back to the title and summary when empty.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Full URL. Only set when this content lives elsewhere first.
     */
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Outcome first, 12 words max. Shown on the homepage tile.
   */
  outcomeLine: string;
  /**
   * Supporting line under the service page headline. 22 words max. Plain language: name the problem, not the technology.
   */
  summary: string;
  heroVisual:
    | 'email-row'
    | 'ledger'
    | 'workflow-node'
    | 'kpi-tiles'
    | 'filter-panel'
    | 'slack-message'
    | 'table'
    | 'chart'
    | 'agent-trace';
  problem: {
    headline: string;
    body: string;
    visual?:
      | (
          | 'email-row'
          | 'ledger'
          | 'workflow-node'
          | 'kpi-tiles'
          | 'filter-panel'
          | 'slack-message'
          | 'table'
          | 'chart'
          | 'agent-trace'
        )
      | null;
  };
  capabilities?:
    | {
        title: string;
        body: string;
        visual:
          | 'email-row'
          | 'ledger'
          | 'workflow-node'
          | 'kpi-tiles'
          | 'filter-panel'
          | 'slack-message'
          | 'table'
          | 'chart'
          | 'agent-trace';
        id?: string | null;
      }[]
    | null;
  /**
   * Used in the URL. Generated from the title if left empty.
   */
  slug: string;
  order?: number | null;
  /**
   * The most in-demand service. Gets the large homepage tile.
   */
  featuredOnHome?: boolean | null;
  faqs?: (number | Faq)[] | null;
  relatedCaseStudies?: (number | CaseStudy)[] | null;
  /**
   * Optional. Falls back to the title and summary when empty.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Full URL. Only set when this content lives elsewhere first.
     */
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'process' | 'ownership' | 'communication' | 'payments' | 'support';
  /**
   * Show 5–6 on the homepage.
   */
  showOnHome?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Created only by the /quote form. Requests marked Lost are deleted automatically 12 months after they arrive.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests".
 */
export interface QuoteRequest {
  id: number;
  status: 'new' | 'contacted' | 'call-booked' | 'quoted' | 'won' | 'lost';
  projectType: 'automation' | 'internal-tool' | 'ai-agent' | 'web-app' | 'not-sure';
  timeline: 'asap' | '1-3-months' | 'exploring';
  stage: 'idea' | 'replace-tool' | 'extend-product';
  name: string;
  email: string;
  company?: string | null;
  description: string;
  source?: ('search' | 'linkedin' | 'referral' | 'blog' | 'other') | null;
  /**
   * Internal only. Never shown to the requester.
   */
  notes?: string | null;
  meta?: {
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
    landingPage?: string | null;
    referrer?: string | null;
    country?: string | null;
    userAgentHash?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-hits".
 */
export interface RateLimitHit {
  id: number;
  key: string;
  bucket: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'purgeLostLeads' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'purgeLostLeads' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'quote-requests';
        value: number | QuoteRequest;
      } | null)
    | ({
        relationTo: 'rate-limit-hits';
        value: number | RateLimitHit;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  slug?: T;
  publishedAt?: T;
  topics?: T;
  featured?: T;
  series?: T;
  author?: T;
  relatedCaseStudies?: T;
  readingTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  problemLine?: T;
  outcomeLine?: T;
  demoUrl?: T;
  repoUrl?: T;
  coverMedia?: T;
  coverPoster?: T;
  coverVisual?: T;
  atAGlance?:
    | T
    | {
        problem?: T;
        solution?: T;
        result?: T;
      };
  problem?: T;
  problemDiagram?:
    | T
    | {
        nodes?:
          | T
          | {
              label?: T;
              detail?: T;
              highlight?: T;
              id?: T;
            };
        id?: T;
      };
  featureShots?:
    | T
    | {
        title?: T;
        caption?: T;
        media?: T;
        visual?: T;
        id?: T;
      };
  architecture?:
    | T
    | {
        nodes?:
          | T
          | {
              label?: T;
              detail?: T;
              highlight?: T;
              id?: T;
            };
        id?: T;
      };
  architectureSvg?: T;
  architectureNotes?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  results?:
    | T
    | {
        value?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  stack?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  slug?: T;
  industry?: T;
  services?: T;
  timeline?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  outcomeLine?: T;
  summary?: T;
  heroVisual?: T;
  problem?:
    | T
    | {
        headline?: T;
        body?: T;
        visual?: T;
      };
  capabilities?:
    | T
    | {
        title?: T;
        body?: T;
        visual?: T;
        id?: T;
      };
  slug?: T;
  order?: T;
  featuredOnHome?: T;
  faqs?: T;
  relatedCaseStudies?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  showOnHome?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quote-requests_select".
 */
export interface QuoteRequestsSelect<T extends boolean = true> {
  status?: T;
  projectType?: T;
  timeline?: T;
  stage?: T;
  name?: T;
  email?: T;
  company?: T;
  description?: T;
  source?: T;
  notes?: T;
  meta?:
    | T
    | {
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
        landingPage?: T;
        referrer?: T;
        country?: T;
        userAgentHash?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limit-hits_select".
 */
export interface RateLimitHitsSelect<T extends boolean = true> {
  key?: T;
  bucket?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The homepage is a sales funnel. Plain language only: no technical terms. Word budgets are hard limits; if copy doesn’t fit, cut copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    /**
     * The hook. Name the pain, not the technology. 10 words max.
     */
    headline: string;
    subhead: string;
  };
  /**
   * 30 words total across both lines.
   */
  beforeAfter: {
    before: string;
    after: string;
  };
  finalCta: {
    headline: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact details and proof. Anything left empty is simply not shown on the site — never add placeholder values.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contactEmail: string;
  /**
   * Shown under the hero CTAs. Only keep it if it’s true.
   */
  responseTime?: string | null;
  /**
   * e.g. "Karachi (UTC+5), overlapping EU and US Eastern hours"
   */
  location?: string | null;
  social?: {
    linkedinUrl?: string | null;
    githubUrl?: string | null;
    /**
     * Public GitHub user or organisation. Enables the contribution graph in the proof strip.
     */
    githubUsername?: string | null;
  };
  /**
   * Only fill in if a real public rating exists (e.g. Clutch, Google). All four fields are required to show it.
   */
  review?: {
    platform?: string | null;
    rating?: number | null;
    count?: number | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subhead?: T;
      };
  beforeAfter?:
    | T
    | {
        before?: T;
        after?: T;
      };
  finalCta?:
    | T
    | {
        headline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contactEmail?: T;
  responseTime?: T;
  location?: T;
  social?:
    | T
    | {
        linkedinUrl?: T;
        githubUrl?: T;
        githubUsername?: T;
      };
  review?:
    | T
    | {
        platform?: T;
        rating?: T;
        count?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPurgeLostLeads".
 */
export interface TaskPurgeLostLeads {
  input?: unknown;
  output: {
    deleted: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language: 'ts' | 'tsx' | 'js' | 'json' | 'bash' | 'sql' | 'python' | 'yaml' | 'css' | 'html' | 'text';
  filename?: string | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  tone: 'note' | 'tip' | 'warning';
  title?: string | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageCaptionBlock".
 */
export interface ImageCaptionBlock {
  image: number | Media;
  caption?: string | null;
  width?: ('content' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageCaption';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  video: number | Media;
  poster?: (number | null) | Media;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  caption?: string | null;
  /**
   * One row per line, cells separated by | . The first line is the header row.
   */
  rows: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'table';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonBlock".
 */
export interface ComparisonBlock {
  leftTitle: string;
  rightTitle: string;
  /**
   * One point per line.
   */
  leftItems: string;
  /**
   * One point per line.
   */
  rightItems: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparison';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  headline: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CaseStudyRefBlock".
 */
export interface CaseStudyRefBlock {
  caseStudy: number | CaseStudy;
  id?: string | null;
  blockName?: string | null;
  blockType: 'caseStudyRef';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureShotBlock".
 */
export interface FeatureShotBlock {
  media: number | Media;
  caption: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featureShot';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}